pipeline {
    stages {
        stage('checkout') {
                steps {
                    git branch: 'main',
                    url: 'https://github.com/tlsrhksgh/recommend_food.git'
                }
            }
        stage('build') {
            steps {
                sh './gradlew build'
                slackSend (
                    color: '#FF0000',
                    message: "STARTED: Job ${env.JOB_NAME} [${env.BUILD_NUMBER}] (${env.BUILD_URL})"
                )
            }
        }
        stage('test') {
            steps {
                sh './gradlew test'
            }
        }
    }
    post {
        success {
            slackSend (
                channel: '#test',
                color: '#00FF00',
                message: "SUCCESS: Job ${env.JOB_NAME} [${env.BUILD_NUMBER}] (${env.BUILD_URL})"
            )
        }
        failure {
            slackSend (
                channel: '#test',
                color: '#FF0000',
                message: "FAILED: Job ${env.JOB_NAME} [${env.BUILD_NUMBER}] (${env.BUILD_URL})"
            )
        }
    }
}